FROM action_fp_conversion
RUN pip3 --no-cache-dir install aws_requests_auth elasticsearch certifi chardet idna requests urllib3 pyutu dynamodb-encryption-sdk cryptography tox moto wheel freezegun sure